on:
  push:
    tags:
      - "v*"

name: Build and Release

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          components: rustfmt, clippy
      - name: Add wasm32-unknown-unknown Target
        run: |
          rustup target add wasm32-unknown-unknown
      - name: Setup node
        uses: actions/setup-node@v2
      - name: Build
        run: |
          yarn build
      - uses: actions/upload-artifact@v2
        with:
          name: card
          path: |
            ./*.js
            ./*.json
            ./card.wasm
            LICENSE
            README.md
  publish:
    name: Publish to npm
    runs-on: ubuntu-latest
    environment: production
    needs: build
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 10
      - run: npm install
      - uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}
