on:
  push:
    tags:
      - "v*"

name: Build and Release

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
          components: rustfmt, clippy
      - name: wasm-pack-action
        uses: jetli/wasm-pack-action@v0.3.0
      - name: Setup node
        uses: actions/setup-node@v2
      - name: Build
        run: |
          git --version
          cargo --version
          yarn --version
          yarn build
      - uses: actions/upload-artifact@v2
        with:
          name: card
          path: |
            ./card_bg.wasm
            ./card_bg.wasm.d.ts
            ./card.d.ts
            ./card.js
            ./package.json
            LICENSE
            README.md
  publish:
    name: Publish to npm
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "17"
          cache: "npm"
      - uses: actions/download-artifact@v2
        with:
          name: card
      - name: Publish
        run: |
          yarn start
          npm config set //registry.npmjs.org/:_authToken ${NPM_TOKEN}
          npm ci
          npm publish
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
